name: Build, test, and deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+-oc*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Extract data from tag: version, message, body"
        id: tag
        run: |
          git fetch --tags --force

      - name: Build
        uses: ./.github/actions

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-latest
          path: build-root/*.deb

  release:
    name: Create and Upload Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create archive
        run: |
          cd linux-latest
          tar -cvzf oneclick-vpp.tar.gz *.deb

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload linux
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-latest/oneclick-vpp.tar.gz
          asset_name: oneclick-vpp.tar.gz
          asset_content_type: application/gzip
